### ISSUE TITLE
 JavaScript heap out of memory when importing

### ISSUE THREAD

**Issue by jannikbuschke** [warrenseine/prettier-plugin-csharp#39] opened 2020-02-05 21:44 UTC
Hi there, thanks for your work, looks promising to me.

Im trying to use your plugin in a react project, where I want to provide users a webeditor that would format their code in the browser.
Im trying the prettier docs here: https://prettier.io/docs/en/browser.html#es-modules, i.e. with your plugin I would assume code along these lines could work:

```js
import prettier from "prettier";
import parser from "prettier-plugin-csharp";

const result = prettier.format("using System ;", {
    parser: "cs",
    plugins: [parser]
});
```
The problem is no matter what I try to import from "prettier-plugin-csharp", starting my project I get a JS heap out of memory error:

```
client-app: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
client-app:  1: 00007FF6AAC8DD8A v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4506
client-app:  2: 00007FF6AAC68886 node::MakeCallback+4534
client-app:  3: 00007FF6AAC69200 node_module_register+2032
client-app:  4: 00007FF6AAF830DE v8::internal::FatalProcessOutOfMemory+846
client-app:  5: 00007FF6AAF8300F v8::internal::FatalProcessOutOfMemory+639
client-app:  6: 00007FF6AB169804 v8::internal::Heap::MaxHeapGrowingFactor+9620
client-app:  7: 00007FF6AB1607E6 v8::internal::ScavengeJob::operator=+24550
client-app:  8: 00007FF6AB15EE3C v8::internal::ScavengeJob::operator=+17980
client-app:  9: 00007FF6AB167B87 v8::internal::Heap::MaxHeapGrowingFactor+2327
client-app: 10: 00007FF6AB167C06 v8::internal::Heap::MaxHeapGrowingFactor+2454
client-app: 11: 00007FF6AB291EA7 v8::internal::Factory::NewFillerObject+55
client-app: 12: 00007FF6AB30F096 v8::internal::operator<<+73494
client-app: 13: 000003DC082DC5C1
client-app: npm ERR! code ELIFECYCLE
client-app: npm ERR! errno 134
client-app: npm ERR! client-app@0.1.0 start: `react-app-rewired start`
client-app: npm ERR! Exit status 134
client-app: npm ERR!
client-app: npm ERR! Failed at the client-app@0.1.0 start script.
client-app: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
client-app: npm ERR! A complete log of this run can be found in:
client-app: npm ERR!     C:\Users\jannik\AppData\Roaming\npm-cache\_logs\2020-02-05T21_35_13_140Z-debug.log
```

Any ideas why this happens?

**Comment by warrenseine** [comment] 2020-02-05 21:55
No, I have no idea. While the plugin loads a generated parser, it’s not really memory-hungry. However, I’ve only tested it in Node, not in a browser.

Can you look at memory usage, see what kind of limit it hits? How did you get that stacktrace?  What is the code running in? Did you really get Chrome to crash or that’s some sort of Electron environment?

**Comment by jannikbuschke** [comment] 2020-02-05 22:20
It is a react application (create-react-app template). It uses webpack as a dev server and as the build tool.

This is the react app: https://github.com/jannikbuschke/csharp-script-runtime-and-editor/tree/master/app/web
In this file Im trying to format code with prettier/your plugin; https://github.com/jannikbuschke/csharp-script-runtime-and-editor/blob/master/app/web/src/scripts/execute-script.tsx

The stack trace is printed to the console when trying to start the react application in debug mode via `npm run start`.
Not sure how to pinpoint this kind of stuff.

**Comment by warrenseine** [comment] 2020-02-06 09:33
I tested locally your project and was able to reproduce the issue. The crash occurs during compilation when including Prettier. Node process memory usage reaches 1.5 GB, whether you include the plugin or not (just call `prettier.format(...)` without the plugin options). I think it would be better to report this problem to the Prettier project instead of the plugin.

Still, I'm curious so I investigated. Raising the Node heap size is enough to fix the problem. See https://github.com/npm/npm/issues/12238#issuecomment-367147962. Problem fixed in my environment: memory usage tops 2 GB and compilation succeeds.

I'm going to close the issue. Don't hesitate to re-open if you think the problem is related to the plugin.

Cool project by the way. Keep me updated if you manage to use `prettier-plugin-csharp`!

**Closed as completed by warrenseine** 2020-02-06 09:33 UTC

**Comment by jannikbuschke** [comment] 2020-02-06 12:06
@warrenseine thanks for looking into this.
I created another repo https://github.com/jannikbuschke/-prettier-standalone-custom-parser to pinpoint the issue further.
One thing that I did wrong was to use the whole "prettier" package, whereas it should be "prettier/standalone".

In the new repo I use prettier/standalone with your plugin as well as with a graphql plugin. The graphql plugin works in both cases. The memory issue comes up only if the prettier-plugin-csharp is imported. Thats why I assume it has something to do with the build system and your plugin.

I created an [issue](https://github.com/prettier/prettier/issues/7557) in the prettier repo, but Im not sure where this really belongs to.

**Comment by warrenseine** [comment] 2020-02-06 16:54
Tested again, and both projects on your new repository compile and run fine here.

**Comment by jannikbuschke** [comment] 2020-02-06 17:34
Are you using node v12? I used v10 and now tested with v12 and it seems to work without changing the memory limit (`--max_old_space_size=4096`). I think this is because v12 allows more memory out of the box.

**Comment by warrenseine** [comment] 2020-02-06 17:45
Indeed.
